### ISSUE TITLE
System for proposing modifications

### ISSUE THREAD

**Issue by PonteIneptique** [hipster-philology/pyrrha#100]
Allez, c'est une discussion importante donc j'ajoute tout le monde.

Dans la situation actuelle, seul-e l'admin peut éditer les listes de contrôle. Ces admins peuvent être plusieurs.

Je voulais à la base proposer aux utilisateur-rice-s d'ajouter des valeurs soumises aux administrateur-rice-s de liste, MAIS il y a une solution potentiellement plus simple : proposer une interface pour envoyer un mail aux admins de ladite liste, qui éditeront la liste ou pourront rentrer dans une discussion avec les personnes concernées.

Cela allégerait le travail de développement et permettrait d'après moi de mieux favoriser les échanges sur ces listes de contrôle...

Qu'en pensez-vous ?

**Comment by architexte** [comment]
Plus simple en effet. Commençons ainsi, et nous verrons à l’usage si une évolution de l’application pour les utilisateurs (propositions de modifs des listes de contrôle) est justifiée.

**Comment by MrGecko** [comment]
Considérablement plus simple en effet

**Comment by Jean-Baptiste-Camps** [comment]
Ok pour commencer comme ça, mais les admins risquent de se retrouver spammés. Maintenir une liste de contrôle de lemmes n'est pas une mince affaire…

**Comment by PonteIneptique** [comment]
@Jean-Baptiste-Camps Sachant tout de même qu'on ne force personne à réutiliser des listes publiques :)

**Comment by PonteIneptique** [comment]
Et on parle bien des admins de liste de contrôle, qui peuvent, comme pour les corpus, partager l'administration des listes.
