### ISSUE TITLE
Tokens get mixed between corpora

### ISSUE THREAD

**Issue by Jean-Baptiste-Camps** [hipster-philology/pyrrha#114]
This a big one: tokens are getting mixed between different corpora, perhaps during the export process. This could be at any step, including during the export from the older instance. 

Some migrated corpora have content mixed with corpora from the older instance, e.g.

- Montferrand and Chrestien;
- Classique_sample_4 and seint Brice

![image](https://user-images.githubusercontent.com/1204247/52731528-34f0d180-2fbe-11e9-8f3a-7821f63340d8.png)

**Comment by PonteIneptique** [comment]
@MrGecko Can we close this one ?
