### ISSUE TITLE
Bug interface de création de corpus

### ISSUE THREAD

**Issue by ArianePinche** [hipster-philology/pyrrha#115]
Bonjour,
Suite à mes petits tests pour préparer une présentation de Pyrrha jeudi, j'ai remarqué quelques petits problèmes dans le page de création de corpus (les bugs semblent aussi bien présents sur le serveur de dev que de prod : 

1. Quand on importe un texte et qu'on le lemmatise, dans les champs le terme "token" apparaît à la place de "form" (ce qui empêche la validation du corpus, en attendant, on peut changer à la main). 
2. Juste en passant, dans l'explication pour l'import d'un tsv/csv, il serait mieux de signaler les champs dans l'ordre soit form, lemma, POS, morph.

**Comment by Jean-Baptiste-Camps** [comment]
En fait, il y a un petit désaccord entre la sortie de Pie, qui appelle le token `token` et le format attendu en entrée par Pyrrha, qui attend `form' (il y a peut-être aussi une différence entre `pos` et `POS`, de tête).
