### ISSUE TITLE
Normal user see add new lemma in control list

### ISSUE THREAD

**Issue by PonteIneptique** [hipster-philology/pyrrha#149]
## Current Behaviour

![image](https://user-images.githubusercontent.com/1929830/92374066-8bbd7f00-f0ff-11ea-8219-8ea524af98e2.png)

0. As a non owner of the control list and a non administrator
1. For a Control List, click the Control List top menu, select a control list. 
2. Click on Lemma on the left menu bar
3. Add New Lemma button appear as shown in the screenshot

## Expected behaviour

The button should not be shown.

**Comment by architexte** [comment]
Normal user see add new lemma in control list… **and should not!**

**Comment by carinedengler** [comment]
We estimate this ticket to take us 0.5d.
