### ISSUE TITLE
Problème de lemmatisation

### ISSUE THREAD

**Issue by Mamerot** [hipster-philology/pyrrha#164]
**Describe the bug**
Erreur lors de la lemmatisation d'un passage tokenisé.

Lors de la lemmatisation du texte tokenisé, au bout de quelques minutes, message d'erreur indiquant de contacter l'administrateur.

Ci-dessous les données tokenisées:

form	lemma	POS	morph
Cist			
titres			
est			
de			
faire			
serement			
de			
verité			
Quant			
li			
plez			
est			
entamez			
il			
covient			
fere			
serement			
de			
verité			
Pour			
ce			
voulons			
nos			
tretier			
del			
serement			
de			
verité			
et			
qant			
il			
doit			
estre			
fez			
et			
en			
quiex			
causes			
et			
quiex			
personnes			
le			
doivent			
fere			
et			
quel			
force			
il			
i			
covient			
garder			
et			
quel			
painne			
cil			
doit			
soffrir			
qui			
ne			
velt			
fere			
serement			
de			
verité			
Serement			
de			
verité			
est			
qant			
aucuns			
jure			
que			
il			
veut			
demander			
ou			
respondre			
par			
bonne			
foi			
et			
non			
pas			
par			
courage			
de			
traveillier			
à			
tort			
son			
aversaire			
si			
comme			
nos			
avons			
en			
Digeste			
vielle			
el			
titre			
De			
partir			
heritages			
en			
une			
loi			
qui			
commence			
Coheredes			
en			
i			
peragrefe			
qui			
commence			
Familie			
herciscunde			
qui			
dit			
einssi			
cil			
qui			
pledent			
par			
jugement			
de			
partir			
heritage			
ou			
de			
partir			
choses			
communes			
ou			
de			
bonner			
terres			
chascuns			
iert			
demandierres			
et			
deffendierres			
Et			
por			
ce			
covient			
il			
fere			
serement			
de			
verité			
que			
li			
uns			
ne			
nuise			
riens			
à			
lautre			
par			
malice			
À			
ce			
meismes			
que			
nos			
avons			
en			
Code			
el			
titre			
De			
fere			
serement			
de			
verité			
en			
la			
seconde			
loi			
del			
titre			
qui			
dit			
einssi			
nos			
ne			
volons			
pas			
fet			
li			
empereres			
que			
li			
juge			
terminent			
les			
causes			
devant			
que			
seremenz			
ait			
esté			
fez			
Ce			
avons			
nos			
en			
Code			
el			
titre			
Des			
jugemenz			
en			
une			
loi			
qui			
commence			
Rem			
non			
novam			
en			
i			
peragrefe			
qui			
commence			
Patroni			
qui			
dit			
einssi			
nos			
volons			
que			
en			
toutes			
les			
terres			
qui			
sont			
soumises			
à			
nostre			
empire			
cil			
qui			
sont			
seingnors			
des			
causes			
facent			
serement			
de			
verité			
et			
puis			
mainent			
le			
plez			
Et			
se			
il			
nos			
semble			
que			
ce			
soit			
necessere			
de			
fere			
ceste			
presente			
loi			
par			
quoi			
nos			
establissons			
que			
en			
touz			
les			
plez			
de			
ci			
en			
avant			
seront			
commencié			
li			
demandierres			
ne			
li			
deffendierres			
naient			
pooir			
de			
riens			
dire			
aprés			
ce			
que			
la			
demande			
avra			
esté			
fete			
et			
que			
len			
i			
avra			
respondu			
devant			
que			
li			
avocat			
de			
chascune			
partie			
aient			
fet			
serement			
de			
deffendre			
loiaux			
causes			
Et			
quant			
les			
principaux			
personnes			
avront			
fet			
serement			
de			
verité			
et			
li			
demandierres			
jurt			
que			
il			
na			
pas			
commencié			
le			
plet			
à			
tort			
à			
son			
escient			
mes			
pour			
ce			
que			
il			
croit			
avoir			
bonne			
cause			
Et			
autressi			
ne			
doit			
pas			
li			
deffendierres			
estre			
oïz			
se			
il			
ne			
jure			
avant			
por			
loial			
entention			
et			
par			
bonne			
ce			
que			
len			
li			
demande			
Et			
aprés			
li			
avocat			
à			
lune			
et			
à			
lautre			
partie			
doivent			
jurer			
seur			
sainte			
Evangile			
de			
Dieu			
si			
comme			
nous			
avons			
establi			
Se			
len			
demande			
qant			
serement			
de			
verité			
doit			
estre			
fez			
generalment			
aprés			
ce			
que			
li			
plez			
est			
entamez			
si			
comme			
nos			
avons			
en			
Code			
en			
la			
seconde			
loi			
del			
titre			
De			
serement			
de			
verité			
que			
nos			
avons			
mis			
devant			
Neporquant			
aucune			
foiz			
fet			
len			
serement			
de			
droite			
verité			
ainz			
que			
li			
plez			
soit			
entamez			
si			
comme			
qant			
li			
deffendierres			
veut			
venir			
à			
la			
cort			
et			
li			
demandierres			
redoit			
estre			
mis			
en			
possession			
de			
ce			
que			
il			
demande			
por			
la			
contumace			
au			
deffendeor			
Et			
einssi			
le			
fet			
len			
à			
Boloingne			
par			
costume			
Et			
nos			
devons			
savoir			
que			
por			
ce			
est			
fez			
cest			
serement			
que			
la			
verité			
soit			
mielz			
esclairiee			
par			
la			
confession			
as			
parties			
et			
por			
deschargier			
les			
parties			
des			
prueves			
et			
que			
la			
force			
des			
jugemenz			
soit			
gardee			
si			
comme			
nos			
avons			
en			
Code			
el			
titre			
De			
fere			
de			
verité			
serement			
en			
la			
seconde			
loi			
del			
titre			
en			
un			
peragrefe			
qui			
commence			
Si			
autem			
qui			
dit			
einssi			
se			
la			
digneté			
ou			
la			
nature			
de			
la			
personne			
notroie			
pas			
que			
elle			
viengne			
par			
devant			
le			
juge			
elle			
face			
en			
sa			
meson			
serement			
de			
verité			
si			
que			
lautre			
partie			
ou			
ses			
procurators			
soit			
presenz			
Et			
il			
meismes			
covient			
que			
ce			
meismes			
soit			
gardé			
se			
ce			
sont			
deffendeor			
ou			
procurator			
ou			
autre			
qui			
aient			
aministration			
dautrui			
choses			
quar			
il			
covient			
que			
il			
face			
serement			
que			
il			
sevent			
bien			
la			
cause			
et			
por			
ce			
la			
maintient			
il			
car			
cil			
qui			
sont			
en			
bataille			
ne			
la			
pueent			
pas			
savoir			
mes			
cil			
qui			
sentremetent			
des			
leur			
choses			
et			
ja			
soit			
ce			
par			
aventure			
que			
la			
verité			
est			
autrement			
nepourqant			
chascun			
puet			
jurer			
ce			
que			
il			
en			
croit			
et			
tuit			
li			
serement			
qui			
ont			
esté			
establi			
ou			
par			
nos			
ou			
par			
autres			
soient			
en			
leur			
forces			
Et			
se			
aucunes			
des			
parties			
ne			
sont			
pas			
presentes			
ainz			
pledent			
par			
procuration			
se			
ce			
est			
li			
demandierres			
il			
nait			
pas			
congié			
de			
demander			
à			
son			
procurateur			
que			
il			
maintiengne			
le			
plet			
se			
il			
meismes			
nen			
fet			
avant			
serement			
de			
verité			
en			
la			
contree			
où			
il			
est			
et			
se			
li			
deffendierres			
nest			
pas			
el			
païs			
ainz			
establist			
procurators			
et			
donne			
caution			
de			
paier			
ce			
qui			
sera			
jugié			
et			
il			
face			
le			
serement			
si			
comme			
nos			
avons			
establi

**Comment by PonteIneptique** [comment]
Closed :)
