### ISSUE TITLE
Problème de recherche de lemme avec caractères accentués dans les listes de contrôle

### ISSUE THREAD

**Issue by Jean-Baptiste-Camps** [hipster-philology/pyrrha#165]
La recherche avec caractères accentués semble ne pas fonctionner,

eg. une recherche `conquerant` trouve `conquérant`

![image](https://user-images.githubusercontent.com/1204247/77433554-cc3e7000-6ddf-11ea-8e28-26b45ac9591d.png)

Mais pas une recherche `conquérant`

![image](https://user-images.githubusercontent.com/1204247/77433604-d9f3f580-6ddf-11ea-947c-d22a005e2f41.png)

**Comment by MrGecko** [comment]
Le correctif proposé permet de trouver **conquérant** dans les deux cas cités au dessus, ce qui pour moi est le comportement attendu.
