### ISSUE TITLE
(Corpus Creation) Check that tokens are not larger than what can be stored in the DB

### ISSUE THREAD

**Issue by PonteIneptique** [hipster-philology/pyrrha#168]
**Describe the bug**
Currently, tokens can be no longer than 64 chars. This means input cannot validate `\S{65, }`. If an error happens

**To Reproduce**
1. Go to New Corpus
2. Fill form
3. Add a token like Pseudosevangeliquolipapistoranabaptistiogiesuitanorbiterondepuritain
4. See error with no details

**Expected behavior**
1. Before submission, a message should be shown about the textarea having a wrong token. Maybe scroll the cursor directly to the problematic line.
2. If it is submitted, because Javascript failed or whatever, the backend should check that tokens are not longer than expected or at least raise a better error.

**Comment by carinedengler** [comment]
We estimated this ticket to take 1d (to take into account possible side-effects we are not conscious of yet).
