### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by gabays** [hipster-philology/pyrrha#174]
**Describe the bug**
When I want to add a new lemma/charge a new lemma list, I get the following answer: "413 Request Entity Too Large"

**To Reproduce**
1. Go to 'control list'
2. Click on 'rewrite lemma list'
3. Try to add a new lemma

**Expected behavior**
Should update the lemma list

**Screenshots**
<img width="616" alt="Screen Shot 2020-04-30 at 19 47 56" src="https://user-images.githubusercontent.com/26046460/80947819-3b50b080-8df1-11ea-885c-2f3804f4d6f3.png">
)

**Desktop (please complete the following information):**
 - OS: Mac OS 1.13
 - Browser Firefox
 - Version 75

**Comment by PonteIneptique** [comment]
You should provide the file for lemmas :) You can drop it if it's .txt

**Comment by PonteIneptique** [comment]
@MrGecko @architexte This clearly looks like an nginx issue. Might be a quick fix ?

**Comment by gabays** [comment]
[lemma-issue.txt](https://github.com/hipster-philology/pyrrha/files/4573550/lemma-issue.txt)

**Comment by PonteIneptique** [comment]
Resolved
