### ISSUE TITLE
Switch control list for existing corpus

### ISSUE THREAD

**Issue by Jean-Baptiste-Camps** [hipster-philology/pyrrha#178]
Sometimes, during corpus creation, an user might get mistaken on the choice of control list. Sometimes too, a control list gets deprecated.

It would be nice to be able to change the control list for an existing corpus, i.e., select a new control list without needing to load the corpus again (and loose history).

**Comment by carinedengler** [comment]
i would say I need 2 workdays for this issue (implementation + tests)
