### ISSUE TITLE
Running Pyrrha on Windows does not work (Py 3.6, 3.7, 3.8)

### ISSUE THREAD

**Issue by ngawangtrinley** [hipster-philology/pyrrha#193]
**Describe the bug**
Installing the tool stops here for me. I've tried by cloning the repo, and by downloading the latest release, both did the same thing.

**To Reproduce**
1. Followed the instructions in the ReadMe
2. Got stuck at `python manage.py db-create`

**Error**
![image](https://user-images.githubusercontent.com/17675331/89054084-cdce0500-d38a-11ea-8bb3-4668324b4bca.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 
**Additional context**

**Comment by PonteIneptique** [comment]
Could you give us more information, most specifically python version and a nice pip freeze :)

**Comment by ngawangtrinley** [comment]
`Python 3.8.5`

blinker==1.4
click==6.7
cov-core==1.15.0
coverage==4.5.3
Flask==1.0.3
Flask-Compress==1.4.0
Flask-Login==0.4.1
Flask-Mail==0.9.1
Flask-Markdown==0.3
Flask-SQLAlchemy==2.4.0
Flask-Testing==0.7.1
Flask-WTF==0.14.2
itsdangerous==0.24
Jinja2==2.11.2
Markdown==3.2.2
MarkupSafe==1.0
mock==3.0.5
nose==1.3.7
nose2==0.6.5
pbr==4.0.3
python-slugify==4.0.0
PyYAML==3.13
redis==2.10.6
rq==0.10.0
selenium==3.141.0
six==1.11.0
SQLAlchemy==1.3.18
text-unidecode==1.3
Unidecode==1.0.23
urllib3==1.25.10
Werkzeug==0.15.3
WTForms==2.2.1

**Comment by ngawangtrinley** [comment]
Just tried with python 3.7 and 3.6 and get the following errors:

## first run error:
![image](https://user-images.githubusercontent.com/17675331/89095914-9f8d0b80-d404-11ea-9584-e80b9c37c964.png)

## second run error:
![image](https://user-images.githubusercontent.com/17675331/89095928-c77c6f00-d404-11ea-84b8-d2d67f064615.png)
![image](https://user-images.githubusercontent.com/17675331/89095944-e0852000-d404-11ea-9b8d-17a5a9de0a51.png)

## pip freeze

blinker==1.4
click==7.1.1
cov-core==1.15.0
coverage==5.2.1
Flask==1.1.2
Flask-Compress==1.4.0
Flask-Login==0.5.0
Flask-Mail==0.9.1
Flask-Markdown==0.3
Flask-SQLAlchemy==2.4.1
Flask-Testing==0.8.0
Flask-WTF==0.14.3
importlib-metadata==1.7.0
itsdangerous==1.1.0
Jinja2==2.11.2
Markdown==3.2.2
MarkupSafe==1.1.1
mock==4.0.2
nose==1.3.7
pbr==4.0.3
python-slugify==4.0.0
PyYAML==3.13
redis==2.10.6
rq==0.10.0
selenium==3.141.0
six==1.14.0
SQLAlchemy==1.3.18
text-unidecode==1.3
Unidecode==1.1.1
urllib3==1.25.10
Werkzeug==0.15.3
WTForms==2.2.1
zipp==3.1.0

**Comment by PonteIneptique** [comment]
Can you remove the database file and retry ?

**Comment by PonteIneptique** [comment]
Note that unfortunately, none of the developers of Pyrrha works with Windows, so you are pretty much testing the waters...

**Comment by PonteIneptique** [comment]
Note that you should not worry about ` SECRET KEY ENV VAR NOT SET! SHOULD NOT SEE IN PRODUCTION`, it's just a warning.

**Comment by ngawangtrinley** [comment]
#197 fixes it. Now working with python 3.8 on Windows 10, 64 bits
