### ISSUE TITLE
fun copy-paste bug 

### ISSUE THREAD

**Issue by ngawangtrinley** [hipster-philology/pyrrha#195]
**Describe the bug**

`ctrl` + `c` in an editable field, then `ctrl` + `v` in another one:

![gif](https://user-images.githubusercontent.com/17675331/89789053-ac230980-db52-11ea-9170-e5eca4b0d858.gif)

**Comment by PonteIneptique** [comment]
Thanks for the report, I'll have a look as soon as I can.
Can you try ctrl + cap + v?

Le lun. 10 août 2020 à 3:46 PM, ngawangtrinley <notifications@github.com> a
écrit :

**Comment by ngawangtrinley** [comment]
I'm on Windows, so ctrl + shift + v, it adds a tab:

copied string: `ཞིབ་`
pasted string: `	ཞིབ་`

**Comment by PonteIneptique** [comment]
Can you tell me what's your browser and its version?

Le lun. 10 août 2020 à 4:31 PM, ngawangtrinley <notifications@github.com> a
écrit :

**Comment by PonteIneptique** [comment]
Can you try the branch `bug//rich-html-paste` (`git pull` then `git checkout bug/rich-html-paste` then the classic python manage.py run` ?

**Comment by ngawangtrinley** [comment]
did just that and I get stuck here:

![image](https://user-images.githubusercontent.com/17675331/89987745-1ce03800-dcb1-11ea-9fd9-f1422f86d216.png)

I tried both creating a new account and using my existing pyrrha account and by creating a new one in the local app, just doesn't go through.

Here's the error message:
![image](https://user-images.githubusercontent.com/17675331/89988321-f40c7280-dcb1-11ea-88bd-4fa7bde0fc83.png)

**Comment by PonteIneptique** [comment]
The mail server is not locally running, which is completely normal.
Normally, the database should not have been touched. Did you start the server from the usual folder you start it from ?
As an addendum, can you confirm the browser you use ?

**Comment by ngawangtrinley** [comment]
Chrome, Version 84.0.4147.125 (Official Build) (64-bit). I did start it from where I usually start it from. 

I downloaded everything again to start from scratch and I'm now getting the following error in the browser:
'sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: corpus'

![image](https://user-images.githubusercontent.com/17675331/89991032-d0e3c200-dcb5-11ea-9ad3-a5d308e21b29.png)

**Comment by PonteIneptique** [comment]
This is extremely weird as I have not been able to reproduce. Will retry.

**Comment by PonteIneptique** [comment]
As for the last code error you have, you simply need to recreate the db: `python manage.py db-create`

**Comment by ngawangtrinley** [comment]
I'm getting everything restarted from scratch in a brand new venv, will send you an update in a few minutes.

**Comment by PonteIneptique** [comment]
Default password and mail :

https://github.com/hipster-philology/pyrrha/blob/13cf3e573860ccb5949ec38103f01d20c422484e/config.py#L29-L30

**Comment by ngawangtrinley** [comment]
meanwhile another issue with Windows in the requirements (I know it's not the place, but we're chatting here):

`Werkzeug==0.15.3` ==> `Werkzeug>=0.15.3`

**Comment by PonteIneptique** [comment]
Feel free to PR for this :)

**Comment by ngawangtrinley** [comment]
Working with the default credentials! Thanks a lot.

**Comment by ngawangtrinley** [comment]
the branch 'bug/rich-html-paste' fixes the issue:
![gif](https://user-images.githubusercontent.com/17675331/89994470-c0821600-dcba-11ea-8acc-8c8899171c7d.gif)
