### ISSUE TITLE
Remove the similar count when browsing

### ISSUE THREAD

**Issue by PonteIneptique** [hipster-philology/pyrrha#201]
The more I use the tool, the more I see people using the tool, the less I see it used. The most important information happens when you save, not when browsing. Given that it's one of the most important bottleneck of the app, I'd vote for removing them.

What do you think @Jean-Baptiste-Camps ?

**Comment by gabays** [comment]
Hello. I am not @Jean-Baptiste-Camps but I have an opinion. I can say that I use the similar count. When I am correcting a brand new corpus and I want to achieve something quickly, I only correct the most frequent mistakes.

**Comment by PonteIneptique** [comment]
Now optional for people who want to use it.
