### ISSUE TITLE
Preference option per corpus

### ISSUE THREAD

**Issue by PonteIneptique** [hipster-philology/pyrrha#203]
**Is your feature request related to a problem? Please describe.**
Currently, it is not possible to:

1. Reset/change the number of words right and left shown in a corpus (`Corpus.context_left` and `Corpus.context_right`)
2. Change the marker of a corpus
3. (New subfeature) Decide to hide / not take into account specific columns such as Morph (some user only tag lemma, some only POS, etc.)
   - This one implies some heavy underlying modifications, including not checking at save time the value of column (ignoring invalid values in unchecked columns)
4. (New subfeature) Decide to show the number of similar (I would probably make this an OPT-IN, while it's on by default).

Those changes would probably enhance UI but also performances from a back-end POV for the last two new subfeature

**Describe the solution you'd like**

1. A new preference page which contains a form with the value up there.
   - Feature (1) needs to regenerate `Token.left_context` and `Token.right_context` for each tokens (visible right now on Create Corpus)
   - Feature (2) changes `Corpus.delimiter_token` (visible right now on Create Corpus)
   - Feature (3) needs checkboxes that explicitly define what to display in columns during corpus edit tokens, and what to be verified.
   - Feature (4) needs a checkbox that hides or show the Similar Column
2. Rework slightly the table macro to shown only relevant columns (Honnestly, the table macro is a mess)
3. Feature (3) will impact <kbd>Change Record</kbd>, <kbd>Search Tokens</kbd> and Verifications at saving time
4. Feature (3) and (4) should create new option for <kbd>New Corpus</kbd>
5. Feature (3) will impact <kbd>Export</kbd> formats
6. Feature (3) should hide <kbd>Unallowed [COLUMN]</kbd> links on the left menu of a corpus page
7. Feature (3) has impact on history page (hides columns), but feature (4) has none, as the similar on this page is `Change Record` similars and not `Token` similar.
8 Feature (3) impact <kbd>Statistics</kbd> page

**Comment by PonteIneptique** [comment]
@MrGecko I don't know if we want this in our current batch of feature for our contractors, but it might be a nice one as well

**Comment by MrGecko** [comment]
Only admins and corpus owners can set and edit these preferences

**Comment by carinedengler** [comment]
@PonteIneptique , @MrGecko I remember from our last meeting that there were on your side some open questions concerning the implications of ignoring (not only hiding) certain columns in the back end. Have you resolved these questions? Can we start developing this last part of the ticket?

**Comment by PonteIneptique** [comment]
I'll take the executive decision here: please go forward, there are no doubts about this feature being requested :)

**Comment by PonteIneptique** [comment]
There was an unforeseen impact which is quite simple: the hiding of column should also affect the `WordToken.get_similar_for_batch(corpus: Corpus, tokens: Iterable["WordToken"])` static method.
