### ISSUE TITLE
integrate flake8

### ISSUE THREAD

**Issue by carinedengler** [hipster-philology/pyrrha#210]
integrate flake8 (with line length 120) into the project and CI, see also #185

**Comment by AdityaJ7** [comment]
Hi @carinedengler  I would like to work on this

**Comment by PonteIneptique** [comment]
Hi @AdityaJ7 ,
Feel free :) It's always nice for new comers to contribute :)

**Comment by AdityaJ7** [comment]
Hi, I don't have much experience with Travis CI, I use Github actions usually, I have made the PR you can suggest changes.

**Comment by PonteIneptique** [comment]
Done by #212
