### ISSUE TITLE
No confirmation email was sent

### ISSUE THREAD

**Issue by johnloque** [hipster-philology/pyrrha#213]
Despite having successfully created a new account, clicked several times on the "Resend confirmation email" button, even repeated the process with another email address, I haven't received anything (it's been approx. 4 hours), and therefore I can't use Pyrrha.

**To Reproduce**
1. go to http://dh.chartes.psl.eu/pyrrha
2. click on 'Register'
3. fill the form
4. wait for a confirmation email

**Desktop :**
 - OS: Linux Mint 20
 - Kernel : Linux 5.4.0-48-generic
 - Browser : Firefox 81.0 (64 bits)

**Comment by PonteIneptique** [comment]
Thanks, can you send me your email address at thibault.clerice CHEZ chartes.psl.eu ? I'll activate it manually until we resolve this bug.

**Comment by PonteIneptique** [comment]
This is a recurring bug. Might be of interest to check what's going on on this front @MrGecko
