### ISSUE TITLE
tests.test_selenium.test_user_account.TestUserAccount errors

### ISSUE THREAD

**Issue by PonteIneptique** [hipster-philology/pyrrha#214]
**Describe the bug**
The test tests.test_selenium.test_user_account.TestUserAccount errors at every run

**To Reproduce**

1. Download / install the repository.
2. Run tests (specifically this one)

**Expected behavior**
The test should not fail.

**Comment by PonteIneptique** [comment]
@MrGecko I don't know if you saw this one, but it has been marking a LOT of PR as failing even though they were not.

**Comment by spencerkee** [comment]
Hi @PonteIneptique, could you assign the issue to me? I'll be able to get started shortly.

**Comment by PonteIneptique** [comment]
Here you go. Thanks!

**Comment by PonteIneptique** [comment]
Hey @spencerkee , sorry I did not welcome you very warmly, I was doing my groceries :) 
Thank you for helping here, let me know if I can help ;)

**Comment by PonteIneptique** [comment]
Fixed by #236
