### ISSUE TITLE
Have a flag preventing sending mail in local or test mode.

### ISSUE THREAD

**Issue by PonteIneptique** [hipster-philology/pyrrha#215]
**Is your feature request related to a problem? Please describe.**
Currently, when running the app without mail server (*ie.* in test mode or local mode), app crashes after registration.

**Describe the solution you'd like**

Something like `app.config["SEND_MAILS"] = True or False` and use it at registration time.

**Comment by saisiddhant12** [comment]
@PonteIneptique 
I think I can work on it and we can solve it by passing boolean to the function and based on this, the mail will be sent or not sent, by default the boolean should be False
Sounds good

**Comment by PonteIneptique** [comment]
Hey @saisiddhant12 !
Nice :)
You can find the line to include in a `if` here: https://github.com/hipster-philology/pyrrha/blob/dev/app/account/views.py#L61
and probably just add a configurable constant here : https://github.com/hipster-philology/pyrrha/blob/dev/config.py#L7

**Comment by saisiddhant12** [comment]
@PonteIneptique I am thinking to add a warning mentioning "Wont be able to trigger mail due to dev env restrictions" and this will be part of logger
Thinking the user should not invest time to de-bug (if not aware about this feature) on why mail is not getting triggered
Do you think it will be a good strategy or should I chuck the logger feature in case of dev environment?

**Comment by PonteIneptique** [comment]
Hmm... I think this is a good idea, it's all about the phrasing:

"Warning, you are using Pyrrha without mail confirmation. If you are running it locally or for development purposes, do not worry about this message. If you are using an online version, well, worry about it." ;)

**Comment by saisiddhant12** [comment]
Perfect I will take this message and generate the logs with these quote 
Looks Funky!

Is it safe to test out the mail feature, or can you give me a temporary mail with creds to test out the feature?

**Comment by PonteIneptique** [comment]
None of the credentials are real here :D So yes. It will definitely crash...
@jhrdt back in https://github.com/hipster-philology/pyrrha/issues/167#issuecomment-704112436 gave the following command 

> I resolved this with `python -m smtpd -n -c DebuggingServer localhost:1025` and using the following config

```
    MAIL_SERVER = 'localhost'
    MAIL_PORT = 1025
    MAIL_USE_TLS = False
    MAIL_USE_SSL = False
    MAIL_USERNAME = ''
    MAIL_PASSWORD = ''
```

**Comment by saisiddhant12** [comment]
@PonteIneptique 
Here is my PR https://github.com/hipster-philology/pyrrha/pull/216
Feel free to review it and keep me posted about the changes required or if you need any clarity

**Comment by PonteIneptique** [comment]
Currently at lunch, I'll get back to you in an hour or two :)
Thanks!

Le mar. 6 oct. 2020 à 12:16 PM, Sai Siddhant <notifications@github.com> a
écrit :

**Comment by PonteIneptique** [comment]
Thanks a lot @saisiddhant12 ! Have a great day :1st_place_medal:
