### ISSUE TITLE
update information based on whether column is hidden or not / or ignore column entirely

### ISSUE THREAD

**Issue by carinedengler** [hipster-philology/pyrrha#229]
#222 allows for hiding columns, but it should also be possible to completely ignore columns as well ; this would imply

* none of the links related to the ignored columns would be visible, e.g. "Unallowed lemma" should not be in the list "Correct tokens with" if "Lemma" is ignored
* the columns in question should not be exported
* the columns in question should not be taken into account for the statistics
* the columns should not be visible in the history of corrections
* the columns should not be taken into account for the 'Similar' column

@MrGecko @PonteIneptique should this be a separate option from 'hide columns'?

related to #203

**Comment by PonteIneptique** [comment]
You are missing the following point:

- the column should not be taken into account at validation time https://github.com/hipster-philology/pyrrha/blob/deb25895d768aa04ec5b87e0202fe933fcdb3921/app/models/corpus.py#L778-L814

I think this should definitely be affected directly by hiding columns. If you hide a column, it does not only mean you don't want to see them, but you are not "caring" about them.

**Comment by carinedengler** [comment]
> You are missing the following point:
> 
>     * the column should not be taken into account at validation time https://github.com/hipster-philology/pyrrha/blob/deb25895d768aa04ec5b87e0202fe933fcdb3921/app/models/corpus.py#L778-L814
> 
> 
> I think this should definitely be affected directly by hiding columns. If you hide a column, it does not only mean you don't want to see them, but you are not "caring" about them.

OK. @FrFerry will be working on this one, so I leave the further discussion in his hands.

**Comment by carinedengler** [comment]
integrate https://github.com/hipster-philology/pyrrha/pull/224#issuecomment-724661626 as well
