### ISSUE TITLE
TSV headers converted into tokens after import

### ISSUE THREAD

**Issue by matgille** [hipster-philology/pyrrha#231]
**Describe the bug**
Headers converted to tokens at importing a corpus (production server)

**To Reproduce**
1. Go to 'Create a new corpus' / paste corpus / tokenize (headers are automatically added) / lemmatize
2. Import corpus
3. See error: the four first tokens are "form", "lemma", "pos" and "morph"

**Comment by PonteIneptique** [comment]
Ok, not a bug, because it's written you should not tokenize THEN lemmatize 
![image](https://user-images.githubusercontent.com/1929830/98545186-64b53200-2295-11eb-8f4e-2fee589ad591.png)

This does mean we need to make this information clearer.

**Comment by matgille** [comment]
Ok, my bad. Maybe add something like "(includes tokenization)" for the lemmatization function and "tokenize only" for the tokenization one...

**Comment by PonteIneptique** [comment]
No worries, this issue raises a design problem. It's completely welcome !
