### ISSUE TITLE
Unable to export tokens for larger corpora

### ISSUE THREAD

**Issue by sonofmun** [hipster-philology/pyrrha#242]
**Describe the bug**
I have a corpus with 42,727 lemmata. When I try to export the tokens for this corpus, the download either fails (with CSV format) or it downloads an incomplete file (with TEI format). I have tested this in Ubuntu 20.04 with Firefox and Chromium and in Windows 10 with Firefox. All show the same behavior.

**To Reproduce**
1. Go to a larger corpus
2. Click on "Export Tokens"
3. Select a format to export
4. Select "Save As..."
5. The result is either an incomplete file or an error.

**Expected behavior**
The file downloads. This seems to work with smaller corpora (works with a corpus with ~12,900 lemmata).

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 and Windows 10
 - Browser: Firefox and Chromium
 - Version Firefox 83, Chromium 87.0.4280.88 (Official Build) snap (64-bit)

**Additional context**

**Comment by PonteIneptique** [comment]
Thanks @sonofmun, we have a PR for this https://github.com/hipster-philology/pyrrha/pull/235, this bug appeared a couple weeks ago and seems to be server specific. We are on this task :)

**Comment by PonteIneptique** [comment]
Fixed :D
