### ISSUE TITLE
Not managing to save corrections 

### ISSUE THREAD

**Issue by apcapc** [hipster-philology/pyrrha#245]
**Describe the bug**

Hello, 

I am trying to implement POS corrections on a corpus (OldCatalan3), and I am not managing to save them. I have tried two browsers and a mac and a windows, and nothing seems to help. I am at a loss as to what I could do to unstuck the tagging. 

Thanks for looking into it. 

Best wishes,

Afra 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by PonteIneptique** [comment]
Hi @apcapc 
Could you guide us a little with a step by step of what you are trying to do and what is shown when you are trying to save ?

**Comment by apcapc** [comment]
Hello,

I am just trying to correct the automatically assigned POS of tokens, starting at 10,0001. For instance, “quiyna” appears blank, and I added WADJ to it, and clicked “save”. It doesn’t get saved, it just keeps swirling. I have tried it in 2 browsers and on a PC (I work on a mac). No idea what might go amiss…

Apologies for the lack of technical understanding of the matter, and thanks for looking into it!

Bonne soirée,

Afra

-- [Graphical user interface, text, application, email  Description automatically generated]

Dr Afra Pujol i Campeny

Affiliated Lecturer
Spanish and Portuguese Section
Modern and Medieval Languages and Linguistics Faculty
University of Cambridge

**Comment by PonteIneptique** [comment]
OH ! I have an idea. Can you reactivate the `Similar` column in your corpus preference/configuration. It seems it is the #244 bug :)

**Comment by apcapc** [comment]
I shall try! Thanks!

--

Dr Afra Pujol i Campeny

Affiliated Lecturer
Spanish and Portuguese Section
Modern and Medieval Languages and Linguistics Faculty
University of Cambridge

**Comment by apcapc** [comment]
Bugger – it is already activated and it doesn’t let me change it (I’ve tried to deactivate it and reactivate it again… no success…)

[Graphical user interface, text, application, chat or text message  Description automatically generated]
--

Dr Afra Pujol i Campeny

Affiliated Lecturer
Spanish and Portuguese Section
Modern and Medieval Languages and Linguistics Faculty
University of Cambridge

**Comment by PonteIneptique** [comment]
I just re-enabled it for you. Does it work ?

**Comment by PonteIneptique** [comment]
(Checked boxes mean columns are disabled. That might be weird use of checkbox...)

**Comment by apcapc** [comment]
The column appears, and I can access the “similar” tokens, but the new POS doesn’t get saved.. It’s still swirling:
[cid:image001.png@01D6E2D3.0BFDFD60]
--

Dr Afra Pujol i Campeny

Affiliated Lecturer
Spanish and Portuguese Section
Modern and Medieval Languages and Linguistics Faculty
University of Cambridge

**Comment by PonteIneptique** [comment]
Bugger. Can you give me the id of the line you are trying to change. I'll try to replicate ;)

**Comment by apcapc** [comment]
10002<https://dh.chartes.psl.eu/pyrrha/corpus/282/tokens/correct?page=101#tok10002>


--

Dr Afra Pujol i Campeny

Affiliated Lecturer
Spanish and Portuguese Section
Modern and Medieval Languages and Linguistics Faculty
University of Cambridge

**Comment by PonteIneptique** [comment]
@MrGecko There is an error 500, so there is definitely something buggy here... Probably tied to the column change we implemented... 
We'll look intoi int @apcapc

**Comment by apcapc** [comment]
Thanks!

--

Dr Afra Pujol i Campeny

Affiliated Lecturer
Spanish and Portuguese Section
Modern and Medieval Languages and Linguistics Faculty
University of Cambridge

**Comment by MrGecko** [comment]
Apparently unrelated to the column change:
```
  File "./app/main/views/tokens.py", line 136, in tokens_correct_single
    morph=string_to_none(request.form.get("morph"))
  File "./app/models/corpus.py", line 1108, in update
    token.label_uniform = unidecode.unidecode(lemma)
  File "/srv/webapp/pyrrha/venv/lib/python3.7/site-packages/unidecode/__init__.py", line 48, in unidecode_expect_ascii
    bytestring = string.encode('ASCII')
AttributeError: 'NoneType' object has no attribute 'encode'

```

**Comment by MrGecko** [comment]
> Hmm yes and no. If column `lemma` is disabled, `lemma` is then `None` and as such can't be decoded :D

I see, I'll look into it asap.

**Comment by PonteIneptique** [comment]
@apcapc That should work soon thanks to @MrGecko work :) test in the few next days :)

**Comment by apcapc** [comment]
Bonjour,

Unfortunately, it is not working yet, so I’ll get annotating manually for the time being.

Thank you so much for looking into it!

Afra

--

Dr Afra Pujol i Campeny

Affiliated Lecturer
Spanish and Portuguese Section
Modern and Medieval Languages and Linguistics Faculty
University of Cambridge

**Comment by PonteIneptique** [comment]
Indeed, it's still bugged

**Comment by MrGecko** [comment]
Hello both of you; I'm deeply sorry but indeed the application needed a restart that, apparently, did not occur as expected. 

@apcapc as a test, I managed to modify the POS of the token 10002 as you can see in the correction history of your corpus.

**Comment by apcapc** [comment]
It does work!

Thank you so much!

Bon vendredi et super weekend à vous!

Afra

--

Dr Afra Pujol i Campeny

Affiliated Lecturer
Spanish and Portuguese Section
Modern and Medieval Languages and Linguistics Faculty
University of Cambridge
