### ISSUE TITLE
OldCatalan4

### ISSUE THREAD

**Issue by apcapc** [hipster-philology/pyrrha#247]
**Describe the bug**
I don't seem to be able to tag anything for PoS on the corpus OldCatalan4 (or correct tags, for that matter). 
I can't alter the PoS list either. 

Theoretically I am the co-owner of the corpus... 

Could you look into it? 

Thanks again! 

Afra 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by PonteIneptique** [comment]
@MrGecko For this one I am a bit lost I must say
@apcapc what's your account ? May I ask you to write the steps you took when you are describing a bug ? This makes all of this a lot easier ;) *ie. :*

**Steps to reproduce**

1. Sign-in
2. Go to https://dh.chartes.psl.eu/pyrrha/corpus/287/tokens/correct
3. Correct POS from token 1 to "P+D"
4. "Invalid value in POS" is shown while it is in the control list.

**Comment by apcapc** [comment]
The account that I use is linked to the email afrapujol@gmail.com<mailto:afrapujol@gmail.com>, the name is Afra Pujol i Campeny (I tried to open one with my university email, but it never worked).

The steps that you describe are exactly right:


  1.  I log in (no prob).
  2.  Try to change the PoS value of any token (for instance, https://dh.chartes.psl.eu/pyrrha/corpus/287/tokens/correct the first token from N to D).
  3.  None of the values on the control list are deemed as valid.
  4.  Additionally, now I am not able to search tokens either (when I try, I end up in the first page of the corpus).
  5.  I cannot alter the values of the PoS control list either…

Thank you so much for looking into it!

Afra

--

Dr Afra Pujol i Campeny

Affiliated Lecturer
Spanish and Portuguese Section
Modern and Medieval Languages and Linguistics Faculty
University of Cambridge

**Comment by MrGecko** [comment]
Hello, I think the control list you use is badly formed: your separator is **', '** instead of **','** and the additional space between elements breaks the machinery.

I suggest you rewrite the POS control list and remove the spaces between the elements.

However, I suggest to leave the issue open since this is a validation issue we should still check or clean when a user submit a control list.

**Comment by PonteIneptique** [comment]
Hmm I can open an issue for the later, and help @apcapc  :)

**Comment by PonteIneptique** [comment]
I fixed the spaces, thanks a lot @MrGecko :)

**Comment by apcapc** [comment]
So sorry for the clumsiness, and thanks!

Afra

--

Dr Afra Pujol i Campeny

Affiliated Lecturer
Spanish and Portuguese Section
Modern and Medieval Languages and Linguistics Faculty
University of Cambridge
