### ISSUE TITLE
Correct typos in Readme

### ISSUE THREAD

**Issue by aurelberra** [hipster-philology/pyrrha#249]
Bonjour. En testant l'application, je signale en passant des corrections à faire dans les consignes :

* "localy" > "locally"
* "-role Administrator" > "--role Administrator"
* " or simply python manage.py edit-user [EMAIL] --confirm-mail -role Administrator if you don't want administrator role" : l'option `--role` devrait être supprimée ici, n'est-ce pas ?

**Comment by PonteIneptique** [comment]
Cher @aurelberra ,
Veux-tu proposer une PR pour cela :) ?

**Comment by aurelberra** [comment]
J'aurai vainement essayé d'éviter ;-) Plus sérieusement, l'option du troisième point est-elle bien une erreur ou y a-t-il une autre option ? Je n'ai pas fouillé le code pour regarder.

**Comment by PonteIneptique** [comment]
Je peux m'en charger effectivement, je regarde ta question et je reviens vers toi.

**Comment by PonteIneptique** [comment]
Voilà ;)

**Comment by aurelberra** [comment]
Parfait ! Comme je n'ai pas de droit d'écriture, mon approbation n'est que symbolique.
