### ISSUE TITLE
Search function gives entire corpus as results

### ISSUE THREAD

**Issue by marklebosch** [hipster-philology/pyrrha#255]
When I want to search tokens in my corpus, the search function always gives all 140.000 tokens as results instead of a precise list of results.

If you want to reproduce the behavior:
1. Go to Corpus
2. Click on 'Search Tokens'
3. Search anything
4. Find everything

I am running Pyrrha on firefox version 88.0.1 on Windows 10, see added screenshots for further context.

<img width="961" alt="screenshot2" src="https://user-images.githubusercontent.com/72186172/118624778-bcdf6a80-b7c9-11eb-87d8-73d1106b3e3d.png">
<img width="949" alt="screenshot1" src="https://user-images.githubusercontent.com/72186172/118624783-bd780100-b7c9-11eb-8503-88a6e9d12d1b.png">

Is anybody else experiencing this? I have close to no IT experience so this might just be my own incompetence at play.

Take care and thanks in advance for your replies

Marc

**Comment by PonteIneptique** [comment]
Hi Marc, 
We are gonna investigate this issue right away... This does not seem like a normal situation !

**Comment by PonteIneptique** [comment]
Hi ! This is finaly completely fixed on https://dh.chartes.psl.eu/pyrrha
Sorry for the delay
