### ISSUE TITLE
Add new columns - Question before pull request

### ISSUE THREAD

**Issue by CVidalG** [hipster-philology/pyrrha#260]
Hi,

I am converting modifications made for the GREgORI project (on the previous version of Pyrrha), for being compatible with your v3.0.

It mainly consists in adding the following columns.

![pyrrha-columns](https://user-images.githubusercontent.com/30558051/128714121-9b17bdd8-ada2-42ec-a652-4ace3f29c3ab.png)

If the text_form, contracted_form, and canonical_Form columns are very dependent on the data structure of the project, the Root and Root_type columns can be used for tagging Semitic languages (e.g. Syriac). Since you can now hide columns (thanks!), would you be interested by such a pull request ?

I don't know where to put the information in the XML output though, maybe would need some help.
Thanks!

**Comment by PonteIneptique** [comment]
Hey Chahan :)
Happy to receive such a pr. I'd recommend two things :
- making sure these are off by default and can be activated at creation
time using a simple check box ("Semitic language" or whatever you see fit).
Could be also activated after :)
- contacting the tei mailing list for the second question. Only apply this
to the msd output, the other one is deprecated :)

Am on the beach for vacations hence my short reply :')

**Comment by CVidalG** [comment]
Thanks Thibault :) I will do that this week!
Bonnes vacances !
