### ISSUE TITLE
Unable to save correction if the token is the last of the table

### ISSUE THREAD

**Issue by matgille** [hipster-philology/pyrrha#261]
**Describe the bug**
I'm unable to save after modifying the last row of a table (in "correct tokens" or after a search).

**To Reproduce**
After modifying the last analysis of a page, clicking on save has no effect.

**Desktop (please complete the following information):**
 - OS: Debian | MacOs Mojave
 - Browser: firefox | firefox
 - Version: 78.13.0esr | 91.0

**Comment by PonteIneptique** [comment]
I love weird bugs :D

**Comment by PonteIneptique** [comment]
NB: the fix is probably easy (pushed something), I just need to deploy now.

**Comment by matgille** [comment]
Great, thank you !

**Comment by PonteIneptique** [comment]
Fixed by @f8e4af9
