### ISSUE TITLE
Add directly a lemma or a pos to a personal dict without modifying anything in a row

### ISSUE THREAD

**Issue by matgille** [hipster-philology/pyrrha#263]
**Is your feature request related to a problem? Please describe.**

For languages with no pre-existing control list, some lemmas will be correct but will need to be added to the control list. When working on unallowed lemmas (or unallowed pos, but it is much easier to constitute a POS/MORPH control list with a small corpus) It would be useful to be able to add the lemma to the personnal dictionnary directly, without having to change anything in the row. 

For now, to add a lemma from a correct analysis, I would need to change something in the row, save, add the lemma to the personnal dictionnary, save, undo the modification. 

**Describe the solution you'd like**
A possibility would be to add to the + button the possibility to add the lemma when displaying all unallowed lemmas, to add the pos for unallowed pos, etc... But I don't know how complicated it would be.

**Comment by PonteIneptique** [comment]
That's a nice feature idea, but quite low on the dashboard I'd say.

> For now, to add a lemma from a correct analysis, I would need to change something in the row, save, add the lemma to the personnal dictionnary, save, undo the modification.

You can also add them by directly going on the `Personal Dictionary` interface.

**Comment by matgille** [comment]
Ok, thanks for the tip !
