### ISSUE TITLE
Local version not having the same features as online version?

### ISSUE THREAD

**Issue by aurelberra** [hipster-philology/pyrrha#269]
In a local version of Pyrrha (re)created today, I don't have access to the same languages for lemmatisation or to the same control lists as in the version online at <https://dh.chartes.psl.eu/pyrrha/>. The screenshots below show the difference. Am I missing something obvious?

I don't suppose this has anything to do with my OS and browser, but will provide the info if it seems useful, of course.

<img width="1056" alt="Screenshot 2022-02-02 at 16 53 16" src="https://user-images.githubusercontent.com/1230441/152195211-f0055459-2669-4021-bbc3-d18507bf2dce.png">
<img width="1049" alt="Screenshot 2022-02-02 at 17 03 56" src="https://user-images.githubusercontent.com/1230441/152195218-2676b8da-1dcc-42a8-a9aa-e05ad4a8405c.png">

**Comment by PonteIneptique** [comment]
Hi Aurelien :)
This is mostly because the lemmatization service is completely decoupled from Pyrrha (it's just something that can be connected to Pyrrha).
For the control list, they are irregularly updated, the online version is probably the most up to date. I could mark it down to update them...

**Comment by aurelberra** [comment]
Thanks for the answer!

What would be the preferred workflow now if I want to use Deucalion and Pyrrha locally, rather than on the Web version?

**Comment by PonteIneptique** [comment]
For the control list, I might be able to update it in the next few days.
For the lemmatizer, it feels to me that using pie-extended locally would be better than going through installing deucalion (which is just an interface for Pie-Extended). ?

**Comment by aurelberra** [comment]
*Merci*!
