### ISSUE TITLE
Lemmatizer crashes for latin text (Lucretius)

### ISSUE THREAD

**Issue by JulieGiovacchini** [hipster-philology/pyrrha#275]
**Impossible to run the lemmatizer**
The lemmatizer cannot process on a txt imported text (6th book of De Rerum Natura by Lucretius). The error message is:
'Operation failed! Contact the administrator with the corpus you tried to lemmatize to investigate the issue.'

**To Reproduce**
1. Go to 'New Corpus'
2. Join a .txt file with latin text in raw format 
First lines:
Primae frugiparos fetus mortalibus aegris
 dididerunt quondam praeclaro nomine Athenae
 et recreaverunt vitam legesque rogarunt
 et primae dederunt solacia dulcia vitae,
cum genuere virum tali cum corde repertum,
 omnia veridico qui quondam ex ore profudit;
4. Click on 'Lemmatize' (I have tried with and without selection of Classical Latin control list)
6. See error

**Expected behavior**
I would like to use the Lemmatizer on latin texts :-)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser : Firefox
 - Version : 98.0.1

**Comment by PonteIneptique** [comment]
Can you try the lemmatizer directly in this interface and tell us what's going on ? https://tal.chartes.psl.eu/deucalion/latin

**Comment by PonteIneptique** [comment]
@JulieGiovacchini We do not have any news from you. Is it resolved ?

**Comment by PonteIneptique** [comment]
Can share with me a text file to try the issue ?
