### ISSUE TITLE
uploading dataset not relating to control list for POS

### ISSUE THREAD

**Issue by dstoekl** [hipster-philology/pyrrha#279]
Despite a POS control list that accepted all POS as valid upon import, once I change anything in the morph (not the POS), any changed POS is flagged as not being in the control list. I can press the button to add it to the control list but the control list does not change. Maybe this is not visible to French who have been working with complete POS, morph, lemma lists for a long time. Try sthg from scratch?

**Comment by PonteIneptique** [comment]
This bug might have been fixed. Can you try again with a new corpus (not the old one) and see if it happens again ?

**Comment by PonteIneptique** [comment]
(Fix on dev, not on the general server)
