### ISSUE TITLE
Erreur de lien token > token en contexte dans le mode recherche

### ISSUE THREAD

**Issue by matgille** [hipster-philology/pyrrha#295]
**Describe the bug**
Il y a une erreur de lien vers le token en contexte dans le mode recherche

**To Reproduce**
1. Effectuer une recherche
2. Cliquer sur l'id du token qui renvoie normalement vers le token en contexte
3. Éprouver l'erreur 404

**Expected behavior**
On devrait arriver à un lien du genre: 
`http://127.0.0.1:5000/corpus/2/tokens/correct?page=2017&limit=100#tok201618`

Et on se trouve face à :
`http://127.0.0.1:5000/corpus/2/tokens/correct?page=2017&per_page=100#tok201618`

La fonction `get_token_uri()` du module `filters.py` est à la cause du problème. Je propose un PR pour corriger cela.

**Comment by PonteIneptique** [comment]
Fixed by #296
