### ISSUE TITLE
500 Internal Server Error on every page

### ISSUE THREAD

**Issue by theolleg65** [hipster-philology/pyrrha#297]
**Describe the bug**
When I try to reach pyrrha, I get  a "500 Internal Server Error" on every  page related to pyrrha. 

**To Reproduce**
1. Go to https://dh.chartes.psl.eu/pyrrha
2. See error

 - OS: Windows 10
 - Browser: Firefox 
 - Version: 118.0.2

**Comment by PonteIneptique** [comment]
Dear Alexander,
Unfortunately, I do not manage this instance. It is dealt by Vincent
Jolivet at the ecole nationale des Chartes ***@***.***)
