### ISSUE TITLE
Capacité à uploader un fichier pour les configurations

### ISSUE THREAD

**Issue by PonteIneptique** [hipster-philology/pyrrha#45]
## Idées

L'upload de fichier vers le serveur semble complètement inutile et pourrait provoquer une surchage à gérer. Par contre, on peut utiliser jQuery/Javascript pour lire le contenu d'un fichier et remplir les textarea :)

## Ressources : 

- https://www.html5rocks.com/en/tutorials/file/dndfiles/
- https://stackoverflow.com/questions/12281775/get-data-from-file-input-in-jquery

### First situation

1. As a normal user, when I create a corpus
2. Click New Corpus
3. Click on <kbd>Write your own</kbd> to show the control list creation as well
3. Fields `#tokens` and `#allowed_lemma`, `#allowed_POS` and `#allowed_morph` need to received huge amount of data, most of the time they are copy pasted

### Second situation

1. As a control list administrator, when I want to edit a control list, 
2. Click on <kbd>Control List</kbd> > Any control list you contorl.
3. On the home page of the control list, 3 yellow buttons are visible, they all start with rewrite
4. On their page, a single field need to received huge amount of data, most of the time they are copy pasted

![image](https://user-images.githubusercontent.com/1929830/92376564-0a67eb80-f103-11ea-9fe2-4b20af00ac03.png)

## Expected Behaviour

Add a button so that

1. User can click upload file
2. The file is read client side and inserted in the text area.

**Comment by PonteIneptique** [comment]
There is a very simple yet working (I think) implementation of this in the following branch : https://github.com/hipster-philology/pyrrha/commit/a129625449a350d9216c27cd870517a0384abdda

**Comment by carinedengler** [comment]
We estimate this ticket to take us 2d.
