### ISSUE TITLE
Possibilités d'avoir des configurations pré-enregistrées

### ISSUE THREAD

**Issue by PonteIneptique** [hipster-philology/pyrrha#52]
Peut-être simplement importer les configurations d'un autre projet ?

**Comment by Jean-Baptiste-Camps** [comment]
L'avantage d'avoir des configurations pré-enregistrées pourrait être de les gérer de manière centralisée (i.e., ajouter un lemme, modifier un POS..) pour tous les projets qui y sont liés. Ce serait pas trop problématique ?

**Comment by PonteIneptique** [comment]
Ce serait pas pour tout de suite, mais en réflechissant à haute voix avec @MrGecko et @architexte, on s'est rendu compte que le passage à l'échelle (en termes d'utilisateur-rice) aller poser un GROS problème de redondance des données. On imagine assez facilement l'impact de 60.000 lemmes * 3 projets * 10 utilisateur-rice-s, alors 100 ou 200 utilisateur-rice-s... Bref.

**Comment by PonteIneptique** [comment]
Possible désormais, mais l'objet configuration sera déjà une grosse avancée.
