### ISSUE TITLE
Inter-corrector agreement

### ISSUE THREAD

**Issue by Jean-Baptiste-Camps** [hipster-philology/pyrrha#61]
Pour info, ce serait cool à un moment d'avoir une fonctionnalité permettant de mesurer l'accord / désaccord entre plusieurs correcteurs sur le même jeu de données. Cela permettrait la constitution plus aisée de corpora gold ou platinum, fondé sur de l'annotation en double ou triple aveugle.
Sûrement pas si simple techniquement…

**Comment by PonteIneptique** [comment]
Tout à fait d'accord, avec un procédé peut-être intégré dans le dashboard, capacité de comparer des corpora disponibles en lecture ?
La fonction pourrait aussi être disponible sur le CLI ?

**Comment by PonteIneptique** [comment]
Tu pourrais citer les statistiques voulues ? Différences générales, par colonne aussi je suppose, combien de différences "uniques" p-e aussi ?

**Comment by Jean-Baptiste-Camps** [comment]
À vrai dire, c'est encore plus simple que des stats, ce que je voudrais. En fait, c'est juste un moyen de revoir systématiquement tous les cas où l'annotation diverge (une page du même genre que celle où l'on revoie les annotations avec 'invalid X', qui serait là 'View tokens with contradictory annotation'). Éventuellement, une stat qui donne le pourcentage pour chaque choix dans le cas où il y ait plus de deux annotateurs, mais c'est encore un niveau supplémentaire.

**Comment by Jean-Baptiste-Camps** [comment]
Donc

```
View tokens with competing annotations

token lemma1 lemma2 ChosenLemma … POS1 POS2… etc. View similar
ce      ce1         ce2
```

Avec comme possibilté bonus, des stats éventuelles, ou le fait que chosenLemma, chosenPos soient alimentés par défaut avec le choix majoritaire quand il existe.

**Comment by PonteIneptique** [comment]
Moved to https://github.com/Chartes-TNAH/pyrrhaCI/issues/5
