### ISSUE TITLE
PPA rename proposal

### ISSUE THREAD

**Issue by PonteIneptique** [hipster-philology/pyrrha#65]
PPA is very awful. It was meant to be a quick app originally and has grown beyond this status. While I'd recommend leaving this repository named this way (or do a link from a new repository), I would like to propose [Pyrrha](https://en.wikipedia.org/wiki/Pyrrha) as the name.

**Comment by Jean-Baptiste-Camps** [comment]
La rousse, donc ?

**Comment by Jean-Baptiste-Camps** [comment]
Ok pour moi.

**Comment by PonteIneptique** [comment]
Done.

**Comment by mikekestemont** [comment]
(Good name.)
