### ISSUE TITLE
Modifier un token

### ISSUE THREAD

**Issue by PonteIneptique** [hipster-philology/pyrrha#71]
Il est possible dans certains cas qu'un token forme doive être modifié.

**Comment by Jean-Baptiste-Camps** [comment]
Oui, Frédéric argumentait en faveur de cela. Mais, de mon côté, je suis plutôt pas convaincu: la modification des valeurs 'tokens' doit plutôt être faite, de mon point de vue, dans le fichier source (souvent xml), pour préserver les enrichissements.

**Comment by PonteIneptique** [comment]
Et en même temps, recharger le corpus pour une typo...

**Comment by Jean-Baptiste-Camps** [comment]
Ou alors, ne pas le recharger, mais corriger la typo dans le fichier source XML ?

**Comment by PonteIneptique** [comment]
Sauf que si tu peux corriger la typo aussi dans le corpus sur Pyrrha, ca veut dire que tu le reconnectes avec le reste des formes. En soi, il faut bien sûr aller corriger le XML, mais empêcher une telle action me parait dommage. Surtout si on travaille avec des extérieurs : la correction de leur XML nous importe peu, ce qui nous intéresse c'est l'export TSV.

Par contre, la dite correction ne se ferait pas sur la même page que la post-correction, pour éviter des erreurs...
