### ISSUE TITLE
Update referentials ?

### ISSUE THREAD

**Issue by Jean-Baptiste-Camps** [hipster-philology/pyrrha#77]
Hello,
I have updated the lemma list for Geste (see https://github.com/Jean-Baptiste-Camps/Geste/tree/master/documentation/profil_annotation and https://github.com/Jean-Baptiste-Camps/Geste/wiki).

Should we update the ppa profiles ?

**Comment by PonteIneptique** [comment]
Yup

**Comment by Jean-Baptiste-Camps** [comment]
See #79

**Comment by PonteIneptique** [comment]
Closed by #79
