### ISSUE TITLE
Rapport utilisateur

### ISSUE THREAD

**Issue by gabays** [hipster-philology/pyrrha#84]
Dans certain cas, la liste pour sélectionner le lemmes ou des POS ne disparaît jamais.
<img width="1048" alt="la liste qui veut pas partir" src="https://user-images.githubusercontent.com/26046460/49664644-beca6e80-fa52-11e8-9c01-8c2bd9937173.png">

Parfois la liste des choix similaires est répétée deux fois (je crois que j'ai changé une fois le lemme, une fois le POS
<img width="1053" alt="bug si 2 cht lemme puis pos" src="https://user-images.githubusercontent.com/26046460/49664814-431cf180-fa53-11e8-9ce9-6912a9354d98.png">

Dans certains cas, lorsque je sélectionne un objet de la liste il me met un retour chariot.
<img width="1052" alt="screen shot 2018-12-07 at 14 25 34" src="https://user-images.githubusercontent.com/26046460/49664842-58921b80-fa53-11e8-8bed-7cc0414fe563.png">

Plus embêtant, j'ai eu plusieurs fois des lemmes validés alors qu'ils étaient absent des "allowed lemmas", et une fois que je les ai ajoutés ils ne sont plus validés…
<img width="1056" alt="screen shot 2018-12-07 at 14 19 55" src="https://user-images.githubusercontent.com/26046460/49664921-9727d600-fa53-11e8-88df-3a327a4b3186.png">

**Comment by PonteIneptique** [comment]
Génial comme retour, me faudrait les informations suivantes : Navigateur, OS, version de Pyrrha utilisée

Ensuite, dans le même genre, la question se porte sur les corpus utilisés avec les listes de configurations, avec une idée pour reproduire les bugs mentionnés :)

**Comment by gabays** [comment]
Firefox 63.0.3, Mac OS 10.13.4. Jean-Baptiste saura te dire pour Pyrrha (corpus theatre_classique_sample4).

**Comment by Jean-Baptiste-Camps** [comment]
Pour Pyrrha, c'est la version sur le serveur de dev. Tu dois pouvoir y retrouver le corpus aussi.

**Comment by Jean-Baptiste-Camps** [comment]
Ah tiens, si, là j'ai le même comportement.

**Comment by PonteIneptique** [comment]
Pour info, normalement le retour chariot n'a pas d'importance dans la sauvegarde. Dois-je comprendre que cela t'a empêché de sauver ?

**Comment by gabays** [comment]
Moi non, car j'ai toujours retiré le retour chariot donc je ne sais pas ce qu'il se passe si je le retire
