### ISSUE TITLE
Problem with the list of lemmas

### ISSUE THREAD

**Issue by floriancafiero** [hipster-philology/pyrrha#85]
Problem occurring using Google Chrome under MacOS, with proper internet connection.

The list of lemma took forever to be fully loaded. When I submitted a modification (addition of three lemmas in my case), the lemmas that were not still loaded were erased of the list.

**Comment by PonteIneptique** [comment]
Damn. I am wondering if there is an issue with the traffic right now because those are bug we never had and I wonder if SQLite is at fault here. Any idea @MrGecko ?

**Comment by Jean-Baptiste-Camps** [comment]
N.B.: we have quite a few lemmas in our list. Around 150 000.

**Comment by floriancafiero** [comment]
Thanks Thibault ! I did not dare suggesting the creation of a "quick-add" function, but that 's what I had indeed in mind ;) 

Obviously, us all editing at the same time quite a long list probably did not help...

**Comment by PonteIneptique** [comment]
150k lemmas ?
You have a shared corpus ?

**Comment by Jean-Baptiste-Camps** [comment]
Yes, it's Theatre_classique_sample4. It's the list from Morphalou + proper names and stuff.

**Comment by PonteIneptique** [comment]
Dealt with using quick edit in #86
