### ISSUE TITLE
"Save X similar" appears twice

### ISSUE THREAD

**Issue by PonteIneptique** [hipster-philology/pyrrha#89]
From #84 "Parfois la liste des choix similaires est répétée deux fois (je crois que j'ai changé une fois le lemme, une fois le POS"

![](https://user-images.githubusercontent.com/26046460/49664814-431cf180-fa53-11e8-9ce9-6912a9354d98.png)

**Comment by Jean-Baptiste-Camps** [comment]
N.B. que la première liste pointe vers la première modif pour l'appliquer en série, et la seconde sur la seconde modif, si je ne dis pas de bêtise.

**Comment by PonteIneptique** [comment]
Donc pour reproduire le bug :
1. Editer la POS
2. Editer la Morph
3. Enjoy.
4. Bug Fix

**Comment by PonteIneptique** [comment]
Fixed a long time ago :D
